# Generated by Django 3.2.4 on 2021-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_alter_botbutton_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbutton',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер кнопки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в TG'),
        ),
    ]
