# Generated by Django 3.2.4 on 2021-08-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_botbutton_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество рефералов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=127b38d47d94db', verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус аккаунта'),
        ),
    ]
