# Generated by Django 3.2.4 on 2021-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20210823_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс от рефералов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=c78e20c470a332', verbose_name='Реферальная ссылка'),
        ),
    ]
