# Generated by Django 3.2.4 on 2021-08-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_auto_20210823_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=c613d2e3db008a', verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Реферал'),
            preserve_default=False,
        ),
    ]
