# Generated by Django 3.2.4 on 2021-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0016_alter_profile_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=0835ce711b953a', verbose_name='Реферальная ссылка'),
        ),
    ]
