# Generated by Django 3.2.4 on 2021-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0023_auto_20210915_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=00228c64ab1f84', verbose_name='Реферальная ссылка'),
        ),
    ]
