# Generated by Django 3.2.4 on 2021-09-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0025_auto_20210928_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='min_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=9ea16087899d40', verbose_name='Реферальная ссылка'),
        ),
    ]
