# Generated by Django 3.2.4 on 2021-10-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0026_auto_20210928_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервис'},
        ),
        migrations.AddField(
            model_name='service',
            name='link_form',
            field=models.TextField(default=0, verbose_name='Формат ссылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=7222bd7810746e', verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.TextField(verbose_name='Сервис'),
        ),
    ]
