# Generated by Django 3.2 on 2022-07-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_auto_20211015_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
                ('subtype_status', models.BooleanField(default=False)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.worktype')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='usersmessage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_count',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='UsersMessage',
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.profile'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.worktype'),
        ),
    ]
