# Generated by Django 3.2 on 2022-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_auto_20211015_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.TextField(default='https://t.me/SimpleSMMBot?start=0afd1365fea53a', verbose_name='Реферальная ссылка'),
        ),
    ]
