# Generated by Django 3.2 on 2022-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0028_auto_20220724_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='employee',
        ),
    ]
