# Generated by Django 3.2 on 2022-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0029_rename_status_profile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='button',
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.BooleanField(default=True, verbose_name='Работник?'),
        ),
    ]
