# Generated by Django 3.2 on 2022-08-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0030_auto_20220730_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botbutton',
            name='number',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='Оповещение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
