# Generated by Django 3.2 on 2022-08-14 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0031_auto_20220814_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='relates_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugc.worktype'),
        ),
    ]
