# Generated by Django 3.2 on 2022-08-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0032_alter_worktype_relates_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='work_type',
        ),
        migrations.CreateModel(
            name='WorkTypeResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.resume')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.worktype')),
            ],
            options={
                'verbose_name': 'Тип работы для резюме',
                'verbose_name_plural': 'Типы работы для резюме',
            },
        ),
    ]
