# Generated by Django 3.2 on 2022-08-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0033_auto_20220814_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
