# Generated by Django 3.2 on 2022-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0035_profile_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbutton',
            name='text_eng',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessage',
            name='text_eng',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
