# Generated by Django 3.2 on 2022-09-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0038_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.BooleanField(default=False, verbose_name='Блокировка'),
        ),
    ]
